models: ["gpt-3.5-turbo-0125", "gpt-4o-mini"]
temperatures: [0.2, 0.7, 1.0]
prompts:
  - "Мәтінді ғылыми стильде, бірақ жаңа сөз қолданып қайта жазыңыз."
  - "Келесі мәтінді жастар сленгімен қайта құрыңыз."

styles: [""]

max_tokens: 600
truncate_input_tokens: 900
